development: &development
  :adapter: redis
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

test: *development

production: &production
  :adapter: redis
  :url: redis://h:pd0b5dfaf1e3c37f81f3401fcc7bcb03ba17a84a8996c39d7da39d491b2da1894@ec2-18-210-203-66.compute-1.amazonaws.com:31519
  :host: ec2-18-210-203-66.compute-1.amazonaws.com
  :port: 31519
  :password: pd0b5dfaf1e3c37f81f3401fcc7bcb03ba17a84a8996c39d7da39d491b2da1894
  :inline: true
  :timeout: 1
