# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveRecord::Base.connection.execute('DELETE FROM users;UPDATE "sqlite_sequence" SET "seq" = 0 WHERE "name" = "users"')
ActiveRecord::Base.connection.execute('DELETE FROM emails;UPDATE "sqlite_sequence" SET "seq" = 0 WHERE "name" = "emails"')
ActiveRecord::Base.connection.execute('DELETE FROM messages;UPDATE "sqlite_sequence" SET "seq" = 0 WHERE "name" = "messages"')
email1 = Email.create(email: "joedimaggio@example.net", primary: true, confirmed: true)
user1 = User.create(username: "joe", email: email1, password: "password" )
email2 = Email.create(email: "herbmontoya@example.net", primary: true, confirmed: true)
user2 = User.create(username: "herb", email: email2, password: "password" )
email3 = Email.create(email: "vanbueren@example.net", primary: true, confirmed: true)
user3 = User.create(username: "vanbueren", email: email3, password: "password" )
email4 = Email.create(email: "leonardo@example.net", primary: true, confirmed: true)
user4 = User.create(username: "leo", email: email4, password: "password" )
email5 = Email.create(email: "sammy@example.net", primary: true, confirmed: true)
user5 = User.create(username: "sammy", email: email5, password: "password" )
email6 = Email.create(email: "becky@example.net", primary: true, confirmed: true)
user6 = User.create(username: "becky", email: email6, password: "password" )
email7 = Email.create(email: "talia@example.net", primary: true, confirmed: true)
user7 = User.create(username: "talia", email: email7, password: "password" )
email8 = Email.create(email: "spencer@example.net", primary: true, confirmed: true)
user8 = User.create(username: "spencer", email: email8, password: "password" )
email9 = Email.create(email: "gonzales@example.net", primary: true, confirmed: true)
user9 = User.create(username: "gonzo", email: email9, password: "password" )
email10 = Email.create(email: "victor@example.net", primary: true, confirmed: true)
user10 = User.create(username: "victor", email: email10, password: "password" )

Message.create(body: "Hello, everyone!", user: user7)
Message.create(body: "What's up!", user: user1)
Message.create(body: "Heyyyy, folks!", user: user3)
Message.create(body: "Hola!", user: user2)
Message.create(body: "What's poppin'", user: user4)
Message.create(body: "Howdy!", user: user3)
Message.create(body: "Well, this is a sprightly bunch!", user: user5)
Message.create(body: "Hey, hey, heyyyyyy, people!", user: user6)
Message.create(body: "Good to see everyone here", user: user8)
Message.create(body: "Hola, mis amigos!", user: user9)
Message.create(body: "What's cookin'?", user: user10)